### ISSUE TITLE
Rename project to tern-webidl

### ISSUE THREAD

**Issue by angelozerr** [othree/webidl-to-tern-def#1]
It should be cool, if you could rename the project to tern-webidl   and add in the package.json "main": "webidl.json" to be consumable by tern. See http://ternjs.net/doc/manual.html#plugin_third_party

**Comment by othree** [comment]
This project is for translate from webidl to tern def(including scripts, data, logs).
I will create another project when the file is ready.
Its almost ready for 1st release.

Thanks for your advice.

**Comment by angelozerr** [comment]
@othree please ping me when you will create this project. I will integrate it inside https://github.com/angelozerr/tern.java

Thanks!

**Comment by othree** [comment]
Should be ok to use https://github.com/othree/tern-webidl
